name: Node.js Package publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
#       - run: npm ci
#       - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: publish
        run: |
            python -u ./setup.py
            cd ./packages/jet-plan-ui
            npm install
            npm publish
            cd ../jet-plan-ui-theme
            npm install
            npm publish
#       - run: npm publish ./packages/jet-plan-ui-theme
#       - run: npm publish ./packages/jet-plan-ui
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
