# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

# on:
#   release:
#     types: [created]
    
on: [push, delete, create]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
#       - run: npm ci
#       - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: publish
        run: |
            cd ./packages/jet-plan-ui
            npm install
            npm publish
            cd ../jet-plan-ui-theme
            npm install
            npm publish
#       - run: npm publish ./packages/jet-plan-ui-theme
#       - run: npm publish ./packages/jet-plan-ui
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
