name: Node.js Package publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
  #       - run: npm ci
  #       - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: publish-JET-UI
        run: |
          ls -a
          python -u ./setup.py
          npm install
          npm publish

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
