name: Sync Github Repos To Gitee
 
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
 
    - name: Sync Github Repos To Gitee  # 名字随便起
      uses: Yikun/hub-mirror-action@v1.1  # 使用Yikun/hub-mirror-action
      with:
        src: github/abchiyi  # 源端账户名(github)
        dst: gitee/abchiyi  # 目的端账户名(gitee)
        dst_key: ${{ secrets.SSH_PRIVATE_KEY.GITEE_PRIVATE_KEY }}  # SSH密钥对中的私钥
        dst_token:  ${{ secrets.SSH_PRIVATE_KEY.GITEE_TOKEN }}  # Gitee账户的私人令牌
        account_type: user  # 账户类型
        clone_style: "https"  # 使用https方式进行clone，也可以使用ssh
        debug: true  # 启用后会显示所有执行命令
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "Jet-Plan-UI"  # 静态同步列表，在此填写需要同步的仓库名称，可填写多个
        timeout: '600s'  # git超时设置，超时后会自动重试git操作
